version: '3'
services:
  cds:
    image: asushares/cds:latest
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - ORG_NAME=My Consent CDS
      - ORG_URL=https://www.your_company.com
      - FHIR_BASE_URL=http://hapi:8080/fhir
    depends_on:
      - hapi
  hapi:
    image: hapiproject/hapi:v6.8.3
    ports:
      - 8080:8080
    environment:
      - hapi.fhir.fhir_version=R5
